Notification service v1
RedHatInsights/ccx-notification-service pull request #29
Opened 2021-04-29 10:32 UTC by epapbak

# Description

Incomplete but working version of the notification service.

- Config files have been cleaned up. Removed values are expected to be set in deployment environment.
- Differ produces 1 notification per cluster with important and critical issues.
- Updated constants for notification message (fields expected by the email template and such)
- Use the timestamp of the selected reports as timestamp for the notified issues
- Notify issues with total risk higher or equal to 3 instead of 2
- Make the notification message comply with the expected format (JSON string with escaped strings inside) 
- Fix some errors in the code (e.g Kafka producer was set and closed for each cluster), added some error control and basic logging.
- Added TODOs for code that is part of other tasks

Fixes #28 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update
- Refactor (refactoring code, removing useless files)

## Testing steps

Mostly manual testing while preparing the demo.

## Checklist
* [x] `make before_commit` passes
* [ ] updated documentation wherever necessary
* [x] added or modified tests if necessary
* [ ] updated schemas and validators in [insights-data-schemas](https://github.com/RedHatInsights/insights-data-schemas) in case of input/output change

2021-04-29 10:57 UTC, tisnik requested changes
LGTM in overall

2021-04-29 10:57 UTC, tisnik commented on PoC-differ/differ.go
> +		if len(deserialized.Reports) != 0 {
probably the opposite condition would be better, as "happy path" in Go points down, not to the left

2021-04-30 20:01 UTC, epapbak commented on PoC-differ/differ.go
> +		if len(deserialized.Reports) != 0 {
Done! Thanks for the tip

2021-05-11 06:45 UTC, tisnik approved these changes
LGTM

2021-05-11 06:57 UTC, merged